# Generated by Django 4.0.4 on 2024-02-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rb_rest_connect_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('connection_name', models.CharField(max_length=255)),
                ('connection_type', models.CharField(max_length=255)),
                ('auth_type', models.CharField(max_length=255)),
                ('auth_url', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.CharField(blank=True, max_length=500, null=True)),
                ('password', models.CharField(blank=True, max_length=500, null=True)),
                ('data_enpoint_url', models.CharField(max_length=2000)),
                ('method', models.CharField(max_length=50)),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.IntegerField()),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('delete_flag', models.CharField(default='N', max_length=1)),
            ],
            options={
                'db_table': 'rb_rest_connect_table',
            },
        ),
        migrations.AddField(
            model_name='rb_db_connect_table',
            name='account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rb_db_connect_table',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rb_db_connect_table',
            name='schema_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rb_db_connect_table',
            name='warehouse_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rb_db_connect_table',
            name='database_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rb_db_connect_table',
            name='host_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rb_db_connect_table',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rb_db_connect_table',
            name='service_name_or_SID',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
