# Generated by Django 4.0.4 on 2024-02-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rb_rest_connect_table_rb_db_connect_table_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query_builder_table_alias',
            name='alias_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
